name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # ---------------------------
  # 1. Build Stage
  # ---------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

  # ---------------------------
  # 2. Test Stage
  # ---------------------------
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

  # ---------------------------
  # 3. Deploy Stage
  # ---------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      pages: write        
      id-token: write     
    environment:
      name: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4